<#
.SYNOPSIS
    Synthesizes Spanish speech with female Colombian accent (es-CO-SalomeNeural) and plays it back.
.DESCRIPTION
    Complies with TASK_AUTOMATION_HARNESS.md.
    1. Validates environment and input text.
    2. Synthesizes high-fidelity audio with Microsoft Neural TTS (Salomé - Colombia).
    3. Saves generated audio artifact in artifacts/.
    4. Immediately plays back the audio via system speakers.
    5. Emits execution logs and standardized KPI reports.
.PARAMETER Text
    The text string to synthesize. If omitted, uses the configured default text.
.PARAMETER DryRun
    Simulates execution without performing synthesis or audio playback.
.PARAMETER NoPlay
    Generates the audio artifact without playing it through the speakers.
.EXAMPLE
    .\tasks\synthesize_colombian_speech\run.ps1 -Text "¡Hola! ¿Cómo estás? Qué gusto saludarte."
.EXAMPLE
    "Prueba de audio desde PowerShell" | .\tasks\synthesize_colombian_speech\run.ps1
#>
[CmdletBinding()]
param (
    [Parameter(Mandatory=$false, Position=0, ValueFromPipeline=$true)]
    [string]$Text,
    [switch]$DryRun,
    [switch]$NoPlay,
    [Alias("NoPauseMedia")]
    [switch]$NoPauseYouTube
)

# 1. Strict Configuration & Directory Isolation
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

$TaskDir     = $PSScriptRoot
$LogDir      = Join-Path $TaskDir "logs"
$ReportDir   = Join-Path $TaskDir "reports"
$ArtifactDir = Join-Path $TaskDir "artifacts"
$BackupDir   = Join-Path $TaskDir "backups"
$ConfigDir   = Join-Path $TaskDir "config"

New-Item -ItemType Directory -Force -Path $LogDir, $ReportDir, $ArtifactDir, $BackupDir, $ConfigDir | Out-Null
$Timestamp  = Get-Date -Format "yyyyMMdd_HHmmss"
$LogFile    = Join-Path $LogDir "task_$Timestamp.log"
$ReportJson = Join-Path $ReportDir "report_$Timestamp.json"
$ReportMd   = Join-Path $ReportDir "report_$Timestamp.md"

# 2. Step-by-Step Logging
function Write-Log {
    param (
        [Parameter(Mandatory=$true)][string]$Message,
        [ValidateSet("INFO", "WARN", "ERROR", "DEBUG", "ALERT")][string]$Level = "INFO"
    )
    $TimeStr = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $Line = "[$TimeStr] [$Level] $Message"
    
    switch ($Level) {
        "ALERT" { Write-Host $Line -ForegroundColor Red -BackgroundColor Black }
        "WARN"  { Write-Host $Line -ForegroundColor Yellow }
        "ERROR" { Write-Host $Line -ForegroundColor Red }
        "DEBUG" { Write-Host $Line -ForegroundColor DarkGray }
        default { Write-Host $Line -ForegroundColor Cyan }
    }
    Add-Content -Path $LogFile -Value $Line
}

# 3. Rollback Procedure
function Invoke-Rollback {
    param([string]$Reason = "Execution failure")
    Write-Log "Initiating rollback sequence: $Reason" "WARN"
    $RollbackScript = Join-Path $TaskDir "rollback.ps1"
    if (Test-Path $RollbackScript) {
        & $RollbackScript -Reason $Reason
    }
}

# 4. Main Execution
$StartTime = Get-Date

try {
    Write-Log "Starting task 'synthesize_colombian_speech'..." "INFO"
    
    $PythonScript = Join-Path $TaskDir "run.py"
    if (-not (Test-Path $PythonScript)) {
        throw "Python script not found at: $PythonScript"
    }

    $PyArgs = @()
    if ($Text) {
        $PyArgs += @("--text", $Text)
    }
    if ($DryRun) {
        $PyArgs += "--dry-run"
    }
    if ($NoPlay) {
        $PyArgs += "--no-play"
    }
    if ($NoPauseYouTube) {
        $PyArgs += "--no-pause-youtube"
    }

    Write-Log "Invoking Python engine: python $PythonScript $($PyArgs -join ' ')" "INFO"
    & python $PythonScript @PyArgs

    if ($LASTEXITCODE -ne 0) {
        throw "Python task process exited with non-zero exit code: $LASTEXITCODE"
    }

    # Locate the newest report generated by run.py
    $LatestReport = Get-ChildItem -Path $ReportDir -Filter "report_*.json" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($LatestReport) {
        $ReportData = Get-Content $LatestReport.FullName -Raw | ConvertFrom-Json
        Write-Log "Speech synthesis and playback completed successfully!" "INFO"
        Write-Log "Duration: $($ReportData.total_duration_seconds)s | Audio Size: $($ReportData.audio_bytes) bytes" "INFO"
        if ($ReportData.audio_artifact) {
            Write-Log "Artifact: $($ReportData.audio_artifact)" "INFO"
        }
    }

    exit 0
}
catch {
    Write-Log "Execution failed: $_" "ERROR"
    Invoke-Rollback -Reason $_.Exception.Message
    exit 1
}
