<#
.SYNOPSIS
    Real-time Microphone Stream Listener, "Angel" Wake-Word Trigger, and Whisper Transcription.
.DESCRIPTION
    Complies with TASK_AUTOMATION_HARNESS.md.
    1. Validates audio input devices and loads Whisper model (CPU/CUDA resilient).
    2. Streams audio in real time, detecting wake-word 'angel' (English).
    3. Records voice prompt upon activation until silence timeout.
    4. Transcribes speech using F:/YT-Downloader Whisper technology.
    5. Saves .wav, .txt, .md artifacts, logs, and structured JSON KPI reports.
.PARAMETER DryRun
    Simulates execution without capturing audio from microphone.
.PARAMETER TimeoutSeconds
    Stops listening after N seconds if wake word is not triggered (0 = wait until trigger or Ctrl+C).
.EXAMPLE
    .\tasks\voice_trigger_angel_transcription\run.ps1
.EXAMPLE
    .\tasks\voice_trigger_angel_transcription\run.ps1 -TimeoutSeconds 30
.EXAMPLE
    .\tasks\voice_trigger_angel_transcription\run.ps1 -DryRun
#>
[CmdletBinding()]
param (
    [switch]$DryRun,
    [int]$TimeoutSeconds = 0
)

# 1. Strict Configuration & Directory Isolation
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8

$TaskDir     = $PSScriptRoot
$LogDir      = Join-Path $TaskDir "logs"
$ReportDir   = Join-Path $TaskDir "reports"
$ArtifactDir = Join-Path $TaskDir "artifacts"
$BackupDir   = Join-Path $TaskDir "backups"
$ConfigDir   = Join-Path $TaskDir "config"

New-Item -ItemType Directory -Force -Path $LogDir, $ReportDir, $ArtifactDir, $BackupDir, $ConfigDir | Out-Null
$Timestamp  = Get-Date -Format "yyyyMMdd_HHmmss"
$LogFile    = Join-Path $LogDir "task_$Timestamp.log"

# 2. Step-by-Step Logging
function Write-Log {
    param (
        [Parameter(Mandatory=$true)][string]$Message,
        [ValidateSet("INFO", "WARN", "ERROR", "DEBUG", "ALERT")][string]$Level = "INFO"
    )
    $TimeStr = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $Line = "[$TimeStr] [$Level] $Message"
    
    switch ($Level) {
        "ALERT" { Write-Host $Line -ForegroundColor Red -BackgroundColor Black }
        "WARN"  { Write-Host $Line -ForegroundColor Yellow }
        "ERROR" { Write-Host $Line -ForegroundColor Red }
        "DEBUG" { Write-Host $Line -ForegroundColor DarkGray }
        default { Write-Host $Line -ForegroundColor Cyan }
    }
    Add-Content -Path $LogFile -Value $Line
}

# 3. Rollback Procedure
function Invoke-Rollback {
    param([string]$Reason = "Execution failure")
    Write-Log "Initiating rollback sequence: $Reason" "WARN"
    $RollbackScript = Join-Path $TaskDir "rollback.ps1"
    if (Test-Path $RollbackScript) {
        & $RollbackScript -Reason $Reason
    }
}

# 4. Main Execution
try {
    Write-Log "Starting task 'voice_trigger_angel_transcription'..." "INFO"
    
    $PythonScript = Join-Path $TaskDir "run.py"
    if (-not (Test-Path $PythonScript)) {
        throw "Python task engine script not found at: $PythonScript"
    }

    $PyArgs = @()
    if ($DryRun) {
        $PyArgs += "--dry-run"
    }
    if ($TimeoutSeconds -gt 0) {
        $PyArgs += @("--timeout", "$TimeoutSeconds")
    }

    Write-Log "Invoking Python engine: python $PythonScript $($PyArgs -join ' ')" "INFO"
    & python $PythonScript @PyArgs

    if ($LASTEXITCODE -ne 0) {
        throw "Python task process exited with non-zero exit code: $LASTEXITCODE"
    }

    # Locate the newest report generated by run.py
    $LatestReport = Get-ChildItem -Path $ReportDir -Filter "report_*.json" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($LatestReport) {
        $ReportData = Get-Content $LatestReport.FullName -Raw | ConvertFrom-Json
        Write-Log "Task execution finished with status: $($ReportData.status)" "INFO"
        if ($ReportData.wake_word_detected) {
            Write-Log "Wake-Word detected after: $($ReportData.listen_duration_seconds)s" "INFO"
            Write-Log "Recorded speech duration: $($ReportData.recorded_audio_seconds)s" "INFO"
            Write-Log "Words transcribed: $($ReportData.words_transcribed)" "INFO"
            Write-Log "Audio WAV Artifact: $($ReportData.audio_artifact)" "INFO"
        }
    }

    exit 0
}
catch {
    Write-Log "Execution failed: $_" "ERROR"
    Invoke-Rollback -Reason $_.Exception.Message
    exit 1
}
